### ISSUE TITLE
Try to make the app compatible with the lowest version possible of iOS

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#29]
Some people still use old versions of iOS (9, but sometimes even lower, especially for things like iPod Touch).
What's the minimum compatible version for the app ?

**Comment by Tovkal** [comment]
Right now the lowest version that can run OFF is 9.1. As a general rule in iOS developers usually target the current version of iOS (11 right now) and the one before. We can't go lower than 9.1 at the moment because of some dependencies restrictions.

But 9.1 covers a lot of devices, as per this table on the right: [https://en.wikipedia.org/wiki/IOS_version_history#Versions](url). 

We would have to go to 7.1 to be compatible with the next device that could not be updated further, an iPhone 4. But we can't do that practically, because a lot of OS and language features would not be available.

**Comment by teolemon** [comment]
So users whose device will become incompatible will keep the old version. iOS doesn't have any multiple app scheme ?

**Comment by Tovkal** [comment]
I think if the new app is uploaded to the same iTunes Connect record as the current one, if a user has a non-compatible device (so iOS <9.1) they'll still be able to download the old version but you will not be able to update it anymore.

> Some of your customers may not have a device that's compatible with your latest app version. To allow them to continue using your app, we make the last-compatible version of your app available to them.
