### ISSUE TITLE
Login screen is transparent and garbled

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#379]
![image](https://user-images.githubusercontent.com/1689815/66831915-0fef9c80-ef59-11e9-99cb-8775269ce3a0.png)

**Comment by aleene** [comment]
Looks like an overlay that turned transparant. Need to force it to secondaryBackground.

**Comment by aleene** [comment]
Need to add some code?

**Comment by aleene** [comment]
This one is ok on my ipad

**Comment by SuzGupta** [comment]
Confirming this is fixed since I was the original reporter. Do we have the issue closing process documented somewhere?

**Comment by aleene** [comment]
Not really. But feel free to write something on the github wiki. I started documenting my approach to changes there.

**Comment by SuzGupta** [comment]
Elsewhere (not on open source projects) I have made the argument that the person who writes the fix should not be the person to close the issue, that the issue should be sent back to its author for review. That may not be the right/ a feasible approach here because it assumes people stick around and test fixes in a timely manner.

**Comment by aleene** [comment]
I think I agree with this approach with a time out.
