### ISSUE TITLE
Travis build

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/openfoodfacts-ios#395]
The Travis build does not end. Issue with settings? AlamofireImage?

**Comment by joemcmahon** [comment]
I think it's `carthage update` taking a long time to finish. I've added a `carthage update` wrapped with the Travis incantation recommended at [the Travis site](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) to the `.travis.yml`. Testing and will report.

**Comment by teolemon** [comment]
seems to be fixed. closing
