### ISSUE TITLE
Add/Edit mode refinements

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#732]
![image](https://user-images.githubusercontent.com/1689815/91231393-7292f680-e72d-11ea-9fbf-06927a309b63.png)

**Comment by aleene** [comment]
The Cancel icon is standard IOS behaviour.

**Comment by aleene** [comment]
There is more and more text on the pages, not very nice when you are really using the app. Is more for first time users. We could add the ?-icon to offer explanations on an alert screen.
Any call to action text should be suppressible for experienced users.

**Comment by aleene** [comment]
Actions:

- [x] put a cross instead of a cancel -> Cancel is standard IOS.
- [ ] Add Nova explanation -> Alert with explanation, We could add a link as we do on the main pages.
- [x] Put Nova message in ingredients section
- [x] Hide the message when the score is computed
- [x] Nutriscore text is clipped, put it below the score -> changed this StackView to vertical (was horizontal).
- [x] Hide the nutriscore message below the categories when the score is computed
