### ISSUE TITLE
Remove the .dev domain by default to avoid confusing newcomers

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ios#754]
Remove the .dev domain by defaut to avoid confusing newcomers as to why the app does not work. Let's use production (.org). The impact will be minimal (WRITE test will be run on a given product.

**Comment by tejuamirthi** [comment]
Hey @teolemon 
As I got to learn about this project recently, I feel eligible for suggestion and proposing a solution. The slack community really helped. Particularly **Alex Beaty**, took out his time to understand my issue and sent the below solution(screenshot with description). Thanks to him
As a new comer, I didn't know how to proceed. But I feel this can be done

- We need to change the build settings to change the localhost:8080 into valid .dev domain (we can update readme as well so that the new contributors understand what needs to be done)
- The above wont solve the entire problem, in debug mode we need to make the search request with authentication values of user and password as **"off"** . I'll create a pr for the same because it is needed.


This screenshot shared by **Alex Beaty** which suggests update the debug endpoints with release endpoints and replace **.org** with **.dev** domain for debug mode

![change-build-settings-from-localhost-to-server-api](https://user-images.githubusercontent.com/29634986/94996273-34f17b00-05c1-11eb-95b7-43c84ef3bbc2.png)

**Comment by tejuamirthi** [comment]
Hey @teolemon Refer #758 for the change and after this change It worked fine for me
